import pandas as pd
import numpy as np
import torch
import os
from math import radians, cos, sin, asin, sqrt

# ==========================================
# CONFIGURATION
# ==========================================
# We use the site list generated by process_data.py to ensure alignment
SITE_LIST_FILE = "data/processed/site_list.csv" 
ENV_FILE = "data/raw/seawater temperature/Environmental_History_1985-2024.csv"
OUTPUT_FILE = "data/processed/adjacency_matrix.pt"

# Connection Threshold (in Kilometers)
# Reefs closer than this will be connected in the graph
THRESHOLD_KM = 50.0 

def haversine(lon1, lat1, lon2, lat2):
    #Calculate the great circle distance between two points 
    # Convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # Haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    return c * 6371 # Radius of earth in kilometers

def main():
    print("--- BUILDING SPATIAL GRAPH ---")
    
    # 1. Get Site Coordinates
    # We need to map the Site_IDs from our processed list back to their Lat/Lon
    if not os.path.exists(SITE_LIST_FILE):
        print(f"Error: {SITE_LIST_FILE} not found. Run process_data.py first!")
        return

    target_sites = pd.read_csv(SITE_LIST_FILE)
    print(f"Target Sites: {len(target_sites)}")
    
    # Load Master Env File to get coordinates
    # Use chunks or just read specific cols to be fast
    try:
        env_df = pd.read_csv(ENV_FILE, usecols=['Site_ID', 'Latitude', 'Longitude'])
    except:
        print(f"Critical: Could not read {ENV_FILE}")
        return
    coords = env_df.drop_duplicates(subset=['Site_ID'])
    
    # Merge to ensure we respect the sorted order of the Site List
    merged = pd.merge(target_sites, coords, on='Site_ID', how='left')
    
    # Extract arrays
    lats = merged['Latitude'].values
    lons = merged['Longitude'].values
    num_nodes = len(merged)
    
    # 2. Compute Adjacency Matrix
    adj = np.zeros((num_nodes, num_nodes), dtype=np.float32)
    
    print(f"Computing pairwise distances for {num_nodes} reefs...")
    count = 0
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i == j:
                adj[i, j] = 1.0 # Self-loop
                continue
            
            dist = haversine(lons[i], lats[i], lons[j], lats[j])
            
            # Logic: If distance < Threshold, creates an edge.
            # Weight could be 1 (binary) or 1/dist (weighted).
            # For now, we use Inverse Distance Weighting (closer = stronger)
            if dist <= THRESHOLD_KM:
                adj[i, j] = 1.0 / (dist + 1e-5) # Avoid div by zero
                count += 1
                
    print(f"Graph Built: {count} edges found (Threshold: {THRESHOLD_KM}km)")
    
    # Normalize Row-wise (good for GCNs)
    row_sum = adj.sum(axis=1)
    # Avoid div by zero
    adj_norm = adj / row_sum[:, np.newaxis]
    
    # 3. Save
    torch.save(torch.tensor(adj_norm), OUTPUT_FILE)
    print(f"Saved Adjacency Matrix to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()